### ISSUE TITLE
How to run command with options

### ISSUE THREAD

**Issue by supoved** [csharptest/CSharpTest.Net.Commands#1]
Hello,

I can't figure out how to run command with options.
I have a command with arguments and some options, for example:

```
[Option("applicationPath", DefaultValue = ".")]
string applicationPath {get;set;}

[Command("clean")]
clean(int times){
}
```

How to run clean command and override default value of the option?

**Comment by csharptest** [comment]
An obvious question, it _should_ have an easy answer :)

Ok so there are 2 ways to accomplish this, the first is to use persistent state (my preferred approach).  Do this by adding a finally block to the main program and calling:

```
finally {
    ci.Run(@"SET > %UserProfile%\.myoptions");
}
```

Then on startup this can be reversed... 

```
try {
    ci.SetDefaults();
    ci.Run(@"SET < %UserProfile%\.myoptions");
}
```

Note: Make sure you've provided Set, PipeCommands and IORedirect to the constructor.  You can also ask the ICommandInterpreter for the available options, walk through them, query the value and write the output in any format you want.  Do basically the same to restore.

The other alternative is to execute a batch file against the interpreter.  Sometimes this makes more sense depending on usage:

_commands.txt_

```
SET applicationPath = C:\Foo
clean 5
```

Then simply redirect the input to your executable when running:

```
C:\> MyProgram.exe < commands.txt
```

You get the idea.  We do this a lot in nmake files using inline files to exercise several methods.

Hope that helps!
